import BloodType from './BloodType';
import CivilStatus from './CivilStatus';
import Position from './Position';
import EducationalAttainment from './EducationalAttainment';
import EmployeeAttachment from './EmployeeAttachment';
import EmployeeEligibility from './EmployeeEligibility';
import Gender from './Gender';
import NatureOfEmployment from './NatureOfEmployment';
import Office from './Office';
import VaccinationStatus from './VaccinationStatus';
import ModeOfResignation from './ModeOfResignation';

export default interface Employee {
  id: number;
  idNumber: string | undefined;
  modeOfResignationId: number | undefined;
  resignationDate: Date | undefined;
  firstName: string | undefined;
  middleName: string | undefined;
  lastName: string | undefined;
  extension: string | undefined;
  fullName: string | undefined;
  natureOfEmploymentId: number | undefined;
  employmentDate: Date | undefined;
  yearsInService?: string | undefined;
  birthDate: Date | undefined;
  age?: number | undefined;
  genderId: number | undefined;
  bloodTypeId: number | undefined;
  officeId: number | undefined;
  positionId: number | undefined;
  residenceAddress: string | undefined;
  contactNumber: string | undefined;
  emailAddress: string | undefined;
  gsisNo: string | undefined;
  sssNo: string | undefined;
  philHealthNo: string | undefined;
  pagIbigNo: string | undefined;
  tinNo: string | undefined;
  isActive: boolean | undefined;
  educationalAttainmentId: number | undefined;
  skills: string | undefined;
  vaccinationStatusId: number | undefined;
  civilStatusId: number | undefined;
  height: string | undefined;
  weight: string | undefined;
  salary: number | undefined;
  detailedOfficeId: number | undefined;
  detailedPositionId: number | undefined;
  salaryGrade: number | undefined;
  step: number | undefined;
  office?: Office | undefined;
  position?: Position | undefined;
  natureOfEmployment?: NatureOfEmployment | undefined;
  bloodType?: BloodType | undefined;
  civilStatus?: CivilStatus | undefined;
  gender?: Gender | undefined;
  educationalAttainment?: EducationalAttainment | undefined;
  vaccinationStatus?: VaccinationStatus | undefined;
  employeeEligibilities?: EmployeeEligibility[] | undefined;
  employeeAttachments?: EmployeeAttachment[] | undefined;
  modeOfResignation?: ModeOfResignation | undefined;
  detailedPosition?: Position | undefined;
  detailedOffice?: Office | undefined;

  tempSalary?: string;
  isRegular?: boolean;
}
